name: RevSkyMorph
version: 1.0
main: me.revsky.morph.RevSkyMorph
api-version: '1.20'
author: RevSky
website: https://example.com

commands:
  disguise:
    description: Transform into entity or block
    usage: /disguise <entity>

  undisguise:
    description: Remove disguise
    aliases: [undis]
